/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

import java.awt.Color;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author batista
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        inserirTabela();
        
    }

//    class Colorir extends JLabel implements TableCellRenderer {
//
//        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
//
//            if (0 == 0) {
//                setForeground(Color.RED);
//                setBackground(Color.yellow);
//            } else {
//                setForeground(Color.BLACK);
//            }
//
//            setText(value.toString());
//            return this;
//        }
//    }

    public void inserirTabela() {
        setLocationRelativeTo(null);
        
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(650);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(70);
        
        jTable2.setCellSelectionEnabled(false);
        jTable2.setRowSelectionAllowed(true);
 
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");//Formato da data para ser exibida na tabela

        DateFormat data = DateFormat.getDateInstance();
       
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        ArrayList<Tarefa> listaTf = Agenda.consultaTarefas();
        
        ArrayList<Date> listaDt = new ArrayList<Date>();
        Object[] fila = new Object[model.getColumnCount()];
        for (int i = 0; i < listaTf.size(); i++) {
            fila[0] = listaTf.get(i).getId();
            fila[1] = listaTf.get(i).getDescr();
            fila[2] = sdf.format(listaTf.get(i).getData_hora_entrada());
            fila[3] = sdf.format(listaTf.get(i).getData_vencimento());
            fila[4] = listaTf.get(i).getHora_vencimento();            
            model.addRow(fila);
        }
    }

    /**
     * Tis method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBConsultar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jBConcluirTarefa = new javax.swing.JButton();
        jBNovaTarefa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAREFAS PENDENTES");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição da Tarefa", "Data Entrada", "Data Venci.", "Hora Venc."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 450));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lupa.png"))); // NOI18N
        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(jBConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 130, 50));

        jBExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Excluir.png"))); // NOI18N
        jBExcluir.setText("Excluir Tarefa");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 50));

        jBAtualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atualizar.png"))); // NOI18N
        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jBAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 50));

        jBConcluirTarefa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBConcluirTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aceitar.png"))); // NOI18N
        jBConcluirTarefa.setText("Concluir Tarefa");
        jBConcluirTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcluirTarefaActionPerformed(evt);
            }
        });
        jPanel1.add(jBConcluirTarefa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 50));

        jBNovaTarefa1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBNovaTarefa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        jBNovaTarefa1.setText("Nova Tarefa");
        jBNovaTarefa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovaTarefa1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBNovaTarefa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 840, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        // TODO add your handling code here:
       FrameDtAntiga frameDtAntiga = new FrameDtAntiga();
       frameDtAntiga.setVisible(true);
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        int selecao = jTable2.getSelectedRow();
        if (selecao == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha para excluir! ");
        } else {
            String id = jTable2.getValueAt(selecao, 0).toString();//Pega o id da linha selecionada para excluir do banco
            //System.out.println(id);
            Agenda.delete(Integer.parseInt(id));
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();//exclui a linha da tabela
            model.removeRow(jTable2.getSelectedRow());
            jTable2.setModel(model);
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    public class TabelaTextAreaRenderer extends JTextArea implements TableCellRenderer{  
    // This method is called each time a cell in a column  
    // using this renderer needs to be rendered.  
      
    public  TabelaTextAreaRenderer(){  
        setLineWrap(true);  
        setWrapStyleWord(true);  
          
    }  
      
    public Component getTableCellRendererComponent(JTable table, Object value,  
            boolean isSelected, boolean hasFocus, int rowIndex, int vColIndex) {  
        // 'value' is value contained in the cell located at  
        // (rowIndex, vColIndex)  
  
        if (isSelected) {  
            // cell (and perhaps other cells) are selected  
        }  
  
        if (hasFocus) {  
            // this cell is the anchor and the table has the focus  
        }  
        // Configure the component with the specified value  
        setText(value.toString());  
  
        // Set tool tip if desired  
        setToolTipText((String)value);  
  
        // Since the renderer is a component, return itself  
        return this;  
    }  
  
} 
    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        while (model.getRowCount() > 0) {//Remove as linhas da tabela 
            model.removeRow(0);
        }
        inserirTabela();//inseri os dados atualizados

    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jBConcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcluirTarefaActionPerformed
           int selecao = jTable2.getSelectedRow();
        if (selecao == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione a tarefa para concluir! ");
        } else {
            String id = jTable2.getValueAt(selecao, 0).toString();//Pega o id da linha selecionada para dar o update
            //System.out.println(id);
            Agenda.concluirTarefa(Integer.parseInt(id));
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();//exclui a linha da tabela
            model.removeRow(jTable2.getSelectedRow());
            jTable2.setModel(model);
        }
    }//GEN-LAST:event_jBConcluirTarefaActionPerformed

    private void jBNovaTarefa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovaTarefa1ActionPerformed
        // TODO add your handling code here:
        Frame_Insercao frame = new Frame_Insercao();
        frame.setVisible(true);
    }//GEN-LAST:event_jBNovaTarefa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBConcluirTarefa;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovaTarefa1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
