/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batista
 */
public class FrameDtAntiga extends javax.swing.JFrame {

    /**
     * Creates new form FrameDtAntiga
     */
    public FrameDtAntiga() {
        initComponents();
        inserirTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        JTableHistorico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTableHistorico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTableHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição da Tarefa", "Data Entrada", "Data Venci.", "Hora Venc."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableHistorico.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(JTableHistorico);
        JTableHistorico.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void inserirTabela() {
        setLocationRelativeTo(null);
        
        JTableHistorico.getColumnModel().getColumn(0).setPreferredWidth(30);
        JTableHistorico.getColumnModel().getColumn(1).setPreferredWidth(380);
        JTableHistorico.setCellSelectionEnabled(false);
        JTableHistorico.setRowSelectionAllowed(true);
 
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");//Formato da data para ser exibida na tabela

        DateFormat data = DateFormat.getDateInstance();
       
        DefaultTableModel model = (DefaultTableModel) JTableHistorico.getModel();
        ArrayList<Tarefa> listaTf = Agenda.consultaTarefasAntigas();
        
        ArrayList<Date> listaDt = new ArrayList<Date>();
        Object[] fila = new Object[model.getColumnCount()];
        for (int i = 0; i < listaTf.size(); i++) {
            fila[0] = listaTf.get(i).getId();
            fila[1] = listaTf.get(i).getDescr();
            fila[2] = sdf.format(listaTf.get(i).getData_hora_entrada());
            fila[3] = sdf.format(listaTf.get(i).getData_vencimento());
            fila[4] = listaTf.get(i).getHora_vencimento();            
            model.addRow(fila);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDtAntiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDtAntiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDtAntiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDtAntiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDtAntiga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableHistorico;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
